apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-user-service-deployment
  labels:
    app: chatapp-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-user-service
  template:
    metadata:
      labels:
        app: chatapp-user-service
    spec:
      containers:
      - name: chatapp-user-service
        image: listonfermi/chatapp-user-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: chatapp-user-service-secrets
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-user-service-service
spec:
  type: NodePort
  selector:
    app: chatapp-user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30011